version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=knb_telegram
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d